### ISSUE TITLE
JSON Schema for DOI metadata validation

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#141]
Validate metadata using JSON schema in addition to XSD, supporting more specific validation of attributes.

**Comment by jamhall** [comment]
Hi there! 

I've been testing out the REST API before my company transitions from using the MDS API (being able to send JSON instead of XML is a big enabler for this). Is there any roadmap for when the validation will be stricter? At the moment I can send any type of resourceType, contributorType etc. and it happily accepts it and persists it and creates a DOI (using the test prefix). 

It would be nice if there was a full JSONAPI example like there is for the [XML full example](https://schema.datacite.org/meta/kernel-4.2/example/datacite-example-full-v4.xml)

I'm currently developing a Java client (to be open sourced) for the REST API  and it would be nice to validate my POJOs against a full JSON example. 

On a side note, the new GraphQL API is excellent! Looking forward to using it.

Thank you for your great work
