### ISSUE TITLE
Import missing metadata by client

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#196]
In December 2018 we refactored how metadata records are stored in the database:

* store metadata XML in `dataset` table (for now they are also still stored in `metadata` table)
* store individual metadata attributes in individual columns in dataset table, using JSON format in most cases

To convert the metadata into the new format we have background tasks, mainly `bundle exec rake doi:import all`. Some records were not imported for a number of reasons:

* metadata not validating, e.g. because they use UTF-16 or the metadata is not correct
* hickups in the system as the import tasks puts an enourmous load on the database
* Other errors

The number of records where this process failed and can be checked with the following query: https://doi.datacite.org/dois?page=NaN&query=-creators%3A*%20-aasm_state%3Adraft&sort=-created, which is currently 499k records.

A fix needs to address two issues:

* fix invalid metadata
* rerun the import task, avoiding database timeouts

**Comment by mfenner** [comment]
If possible, avoid any complex queries using SQL, as those will be very slow and might timeout because of the size of the database table.

A better approach would be to identify the DOIs with missing metadata using an Elasticsearch query and then loop through them, ideally broken down into manageable buckets. Use https://github.com/datacite/lupo/blob/master/app/models/doi.rb#L900-L937 as a template.

**Comment by richardhallett** [comment]
I've re-imported around 450k records and now the number from the above query is a lot less, around 29k.
However looking at a lot of these DOI's there are many who do not have any corresponding metadata to import, therefore I am not sure these are any to be concerned about.
I've done a random sample and in most cases there seems to be either no metadata, or potentially bad data from old DOI's, both of which we can't do anything about.
There are also some DOI's in this query that just do not have certain parts of metadata but due to the schema version are still imported fine.

I think we can conclude that this is reasonably fixed for now and close the issue.
