### ISSUE TITLE
Populate Test System with Data.

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#199]
We need a populated instance for User testing, regularly we would do this in the Stage instance but it has no data about usage. We will need to populate the Stage database with DOI that have usage data. Then add reports Stage Hub API so the Stage EventData instance can have the usage data. DOIs from this client have usage data: https://search.datacite.org/works?data-center-id=cdl.ucsfctsi . One can find more in the Event data API.

child https://github.com/crosscite/doi-metadata-search/issues/89"

**Comment by kjgarza** [comment]
Lets do as one off thing. 
Just Copy enough data that we can use it for a few months.

**Comment by richardhallett** [comment]
This is actually potentially tricky to copy this data across.
From my understanding we need all the events associated to DOI's but the doi's need to exist in the test system as well, so there are multiple sets of raw data to copy over.
In addition this is complicated by the fact events data does not have the same index for looking up DOI's. We could however use the API and the ES index to find related eventdata for particular DOI's and write a script to insert, however this is potentially a large amount of work.

Do we have any existing work of getting this eventdata into the test system? or is it possible to just fake it? because that might be simpler.

**Comment by kjgarza** [comment]
Last time we re-created both the DOIs and the Events in the Stage System.

**Comment by kjgarza** [comment]
One alternative, could be that you take full sushi reports from Metrics Hub (api.datacite.org/reports) and re-submit them to the STAGE Metrics Hub (api.test.datacite.org/reports). That way the Hub create all the events in STAGE EventData automatically. But you will still need to create all the DOIs from those reports in the STAGE API.

**Comment by richardhallett** [comment]
This proved a lot more complicated with various errors and trials.
I have though managed to submit a couple of reports and created fake DOI's on the test system across various clients that contain usage.
Here is a list of all the fake DOI's in the test system that have come from live (but with new DOI's) that have usage associated.
[usage-dois.txt](https://github.com/datacite/lupo/files/2915236/usage-dois.txt)
