### ISSUE TITLE
Feedback on REST API documentation

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#201]
We have updated the documentation for the REST API v.2:

* API Reference: https://support.datacite.org/reference/introduction, generated from Open API definition at https://github.com/datacite/lupo/blob/master/openapi.yaml
* REST API Guide: https://support.datacite.org/docs/api

Please provide feedback in the form of comments, suggestions and questions below.

**Comment by croaker000** [comment]
So, my feedback on using the API via PHP to create published DOIs based on the results on the interactive documentation:
1 - curl data needs to be wrapped in a data element (I think that bug has been fixed)
2 - Please remove all read-only fields from the list (or mark as such)
3 - Fields that use a definitive list of options need to be dropdowns listing the valid options
4 - All fields need descriptions of what the content should be
5 - All required fields need to be indicated
6 - The event field ('event':'publish') needs to be highlighted as important for marking DOIs as findable
(I'm not sure it's even in the documentation)

**Comment by acraugh** [comment]
Tech-editing type comments on the "DataCite Rest API Guide" as I'm reading it. Note that while I am an experienced programmer (usually scripting, analysis, and file format conversion) I am not currently an API programmer nor steeped in DataCite interface jargon, so ambiguity in descriptions is particularly problematic for me. 

General comment:  The example results show pretty-printed JSON, but there is no indication that it is possible to request pretty-printed JSON from the API.  This makes direct comparison of command-line results very difficult, when it is possible to get any.

Page: Retrieving a single DOI

- The example URL given is "https://api.test.datacite.org/dois/10.5438/0012", but this URL returns "No match".  The URL "https://api.datacite.org/dois/10.5438/0012" does return results that match the example given.

Page: "Retrieving a list of DOIs"

- 2nd paragraph: Link label "Making and filtering queries" does not correspond to actual page name, which is "Queries and Filtering".
- 3rd paragraph: Link label "pagination" leads to an irrelevant page on a non-DataCite site that does not even contain the word "pagination".  Non-local links should be indicated as they are elsewhere on the docs site.
- "What's in a list?" starts by saying "A list has three parts" and then has a bulleted list with four items in it.  The second item in this list refers to the "?include=x" parameter, without any explanation or reference to another page that might have an explanation. It is not clear whether this is a toggle to either enable/disable the entire category of information, or somehow modifies the type of "include" information returned, or something else.  Since "include" is a term that usually limits or selects returns from queries, its use here as a category of information returned without additional explanation is particularly problematic.
- The extended example output in "What's in a list?" is not particularly helpful.  The list does not match what is actually returned by the query in detail, and is too long to take in visually to see the structure alluded to in the bulleted list.  I think it might be more helpful to indicate the general structure of the returned list and ellide the details than to attempt to show real data for this particular example.  This would, for example, help to clarify the use of "include" in this context.
- "What kind of a list can I ask for?": If this list of resources is complete, then I would argue that six is not "many".  It is a sufficiently small number that some additional explanation of what constitutes each type of resource could and should be provided.  For example, I don't know the different between a "client" and a "provider" in this context.  Some high-level indication of the type of information returned for non-/dois resources would also be appreciated.
- Last paragraph: This references the "next section of this guide" as "Queries and Filtering", but in fact the table of contents in the left panel indicates the next section is "Pagination" (perhaps this is where that non-DataCite link above should have pointed?).

Page: Pagination

- There's a change in terminology on this page vs. the preceding pages that is confusing to novices like me.  This page refers to "records" being returned by a query, whereas the last page ("Retrieving a list of DOIs") refers to a "list" being returned.  It is not clear what constitutes a "record" in the return.  Farther down in the page there is a reference to "objects" in the return data, which is also undefined and unclear in this context where other jargon has been used.
- "Page Number": The first sentence, "Paginate using the page[number] query parameter, starting with 1," is an imperative sentence rather than any sort of explanation or exposition.   The sentence "The sort order can be specified using the sort query parameter" introduces a parameter (apparently - special formatting for parameters found elsewhere is not present here) that goes unexplained.  It would be preferable to include a reference to where "query" is explained, or to alter the sentence to explain that pages are returned in sorted order if one was specified. Better to make that a parenthesized comment, because the current tone and placement make it seem like a "query" usage example is following, but of course it is not.
- The sentence "This is the default if no page[number] or page[cursor] is specified" implies that pagination always happens.  I don't think that is true because of the way things are presented on the "Retrieving a List of DOIs" page, but I'm not sure because I can't easily parse out the response to API commands I'm trying to see if there's a "link" section with a "next" URL in it.
- "Cursor": This paragraph also contains an imperative sentence which is equally odd.  There is also a lack of consistency in formatting that makes it unclear whether words like "next" are referring to labels in the result or are just part of a sentence.  The sentence "The sort order is always created ascending" is confusing - is it referring to the sort order created by the as-yet unexplained "query" parameter, or is it implying that is it possible to retrieve "page number"-type pages in reverse order whereas "cursor"-type pages must be retrieved in strictly increasing order?  But if you only have a "next" pointer, how could it be anything else?  
- It's not clear why there is a difference in the restriction in the total number of records that can be retrieved via the two pagination options, or what the actual restriction is in the "page number" case. Is there a restriction on the number of "page number" pages that can be returned, or is there a restriction on the actual number of records that can be returned regardless of the number of pages?
- Unlike other pages, there is no link to the "next page" at the bottom of this page.

At this point, it seems odd to be that it is not possible to just request the "meta" information without getting the rest of the list.  There has been no indication, as yet, that this is possible. Perhaps it isn't.

Page: Queries and Filtering

- First paragraph refers to "Retrieving a list of DOIs" as "the previous section", but according to the table of contents the previous section was "Pagination". ("Retrieving a list of DOIs" is _a_ previous section. I know, it's picky stuff.)
- All the example queries on this page return "no match".  In this case, removing the "test." part of the URL still yields "no match". 
- The link to Elasticsearch documentation does not indicate that it is not a DataCite URL.  
- It is not clear what the statement "The REST API uses Elasticsearch Query String Queries" is supposed to imply. The page referenced shows the structure used for API queries to an Elasticsearch store.  This is a JSON structure that is nothing like the syntax in the example string.  Perhaps the intention was to link to the part of that page that is titled "Query string syntax", but again the syntax shown in the Elasticsearch documentation is nothing like the syntax in the example - the former uses quotes and spaces which are interpreted in very specific ways, whereas the example use no quotes, is URL-encoded, and the logical interpretation of multiple tokens is not stated (is it "AND" or "OR", specifically, or dependent on actual syntax as it is with Elasticsearch?).  The paragraph seems to explain it, but then does not explain how the URL-encoded example would be interpreted.  Since none of the actual examples on this page work, it is not possible to derive the relationship by running the queries.
- "Field Names": No indication is made of how you might discover what field names are applicable to the various types of resources that may be requested.
- The sentence beginning "For nested fields use the same format as in the REST API response, ..." is confusing.  The only REST API response I've been able to get contains no "." notation for fields - only the nested JSON representation can be returned as far as I can tell.

I'm going to stop here, because at this point I can't run the examples as tests and the descriptions are, consequently, increasingly difficult to understand,

**Comment by mfenner** [comment]
Thanks @croaker000 and @acraugh, very helpful!

**Comment by efgramsbergen** [comment]
I only had a quick look, and here is one comment:
When requesting metadata, the response has, what looks like, a jsonized version of the Datacite xml. But the Datacite version number is missing.

**Comment by acraugh** [comment]
On Thu, 28 Feb 2019, Martin Fenner wrote:

> Thanks @croaker000 and @acraugh, very helpful!

I hope so - sometimes it seems like I only complain!

I am very interested in learning the full details of this interface, so if 
there is more I can do to help with testing or editing documentation, 
please do feel free to contact me. I'm in the process of learning about 
Elasticsearch to set up my own repository here, so I am acquiring some 
additional useful background as well.  And since I've been trying to 
document our own system for novice users, I realize how difficult it is to 
forget that you are an expert and to explain things for new users!

Best regards,

-Anne R.
