### ISSUE TITLE
REST API - contentURL is single string not array

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#227]
contentUrl is documented as being an array, but validated as single string.
Investigate and potentially just update the live API documentation

**Comment by thackerc** [comment]
I apologize for nit picking, but the field name is `contentUrl` not `contentURL` correct? I ask because when I use PUT with any variation of these field names I get:
`{"errors":[{"status":"400","title":"unknown attribute 'contentUrl' for Doi."}]}`

I'm using documentation found at: [https://support.datacite.org/reference/dois-2#put_dois-id](https://support.datacite.org/reference/dois-2#put_dois-id)

Also, Could we go for some consistency with the JSON API and stick with field names that are either `*Url` or `*Uri`?

**Comment by mfenner** [comment]
This has been fixed, API now accepts an array of strings that are URLs.
