### ISSUE TITLE
Empty elements in JSON output not consistent 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/lupo#309]
### Expected Behaviour

empty elements in the JSON output returned in consistent format

### Current Behaviour

empty elements in json seems to be treated two ways: as an empty list (assuming the element is a list), or as null. The empty lists are much more common, so it would be great if the null values could be turned to empty lists.

### Steps to Reproduce

https://api.datacite.org/clients/ucar.ucar/dois 

### Context (Environment)

rest api in production response either

```json
"rightsList":null,
```
or 

```json
"rightsList":[
            ],

```

**Comment by tedhabermann** [comment]
It appears that this issue was interpreted as applying only to the rights_list element. It is actually pervasive and applies to attributes as well as lists. For example, in this creator metadata over half of the fields are empty and that emptiness is represented two different ways:
{
    "name": "Oddział Łódzki Polskiego Towarzystwa Chemicznego",
    "nameType": "Organizational",
    "givenName": null,
    "familyName": null,
    "affiliation": [],
    "nameIdentifiers": []
}
My suggestion would be to avoid outputting empty fields in metadata records.

**Comment by mfenner** [comment]
We are still working on this, but there is a difference in your example, some fields are strings (e.g. givenName), and `null` makes sense, other fields are arrays (e.g. affiliation), and we show an empty array. 

I am not sure hiding fields in the API makes a difference, as a parser still has to handle missing values.

**Comment by tedhabermann** [comment]
I understand the difference between strings and arrays and I agree that null "makes sense" as a value for a missing string. But in a metadata record it changes the question from "does this exist?" to "does this exist and does it have content?" and requires looking at the content to make sure it is real not just something that says there is no content. No one is interested in the person null null.

**Comment by mfenner** [comment]
Maybe there are better examples than `creator`, which is our most complex element in the metadata for a variety of reasons. You will not find a `creator` entry that is empty, but empty `givenName` or `familyName` will be common as this is an optional field and not used for nameType `Organizational`.

**Comment by tedhabermann** [comment]
I agree these are very common. In fact, I am finding organizations with given and family names (actually errors in nameType):
{
    "name": "Mikkonen, Hannah",
    "nameType": "Organizational",
    "givenName": "Hannah",
    "familyName": "Mikkonen",
    "affiliation": "RMIT"
}

I am also finding organization creators with no names. In these cases the affiliation has the name. I think this is bad style.

Also, organizations with names and affiliations...

In the ISO metadata approach, required fields without content are explained with a nilReason attribute (has several standard values) and optional fields with no content are not included in the record. That is what I am used to and I think it makes sense.

**Comment by mfenner** [comment]
There is a very long story behind personal names in the creator field. The short version is that it is broken for lots and lots of DOIs, as the recommendation for `creatorName` (family name, given name) has been ignored by many. We first introduced givenName and familyName, then nameType. Also we are processing all names on registration to check whether they are personal names. For example by using a dictionary of common first names.

Organizations can have name and affiliations in our schema, see the affiliation example for schema 4.3: https://schema.test.datacite.org/meta/kernel-4.3/example/datacite-example-affiliation-v4.xml

**Comment by tedhabermann** [comment]
On the topic of consistency in metadata element types, the affiliation element can be either a string or a list and I expect that this explains the original observation. For example, shown below are the affiliation elements for a sample of doinz.gnssci records. Some are strings, some are lists. I suspect that when the json is created and the affiliation element is empty, if the tool thinks it is a string, it writes out null, if it thinks it is a list, it writes out []. The example below shows what happens when the content is not empty. You get some strings and some lists.

This becomes a problem when I am trying to determine how often a particular affiliation string occurs in a set of records because dictionaries can not use lists as keys. Maybe this type flexibility is just something we need to live with in json land.

[['GNS Science'],
 ['GNS Science'],
 ['University of Waikato'],
 [],
 ['GNS Science'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 'LIAG. Hannover, Germany',
 'GNS Science. Department of Tectonophysics. Lower Hutt, NZ',
 'University of Canterbury. Christchurch, NZ',
 'GNS Science, Department of Active Landscapes. Lower Hutt, NZ',
 'GNS Science, Department of Active Landscapes. Lower Hutt, NZ',
 ['GNS Science'],
 [],
 [],
 [],
 [],
 ['GNS Science'],
 [],
 ['GNS Science'],
 ['GNS Science'],
 ['GNS Science'],
 'GNS Science']

**Comment by mfenner** [comment]
This is a bug that is only partically fixed. When it is fixed, `affiliation` will always be an array of objects, where the object has key `name` and optional keys `affiliationIdentifier`, etc.
