### ISSUE TITLE
[Graphql] CitationsOverTime gives weird counts distribution

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#601]
### Expected Behaviour

CitationsOverTime should return a distribution of citations binned by the publication date of the newest doi in the relation of the events.

This was implemented using `citation_year` in the index:

```
 def citation_year
    "" unless INCLUDED_RELATION_TYPES.include?(relation_type_id)
    subj_publication = subj['date_published'] || (date_published(subj_id) || year_month)
    obj_publication =  obj['date_published']  || (date_published(obj_id) || year_month)
    [subj_publication[0..3].to_i, obj_publication[0..3].to_i].max
  end


```

We discussed this feature in:

- https://github.com/datacite/lupo/issues/313
- https://github.com/datacite/lupo/pull/330
- https://github.com/datacite/lupo/commit/2390b78404792d6aba354f22fff923c930e3dd1b

### Current Behaviour

CitationsOverTime is retuning  a distribution of citations binned by the `occurred_at` date in the event.

see: https://github.com/datacite/lupo/blob/a2a6743/app/models/doi.rb#L1171

```
  # remove duplicate citing source dois,
  # then show distribution by year
  def citations_over_time
    citation_events.pluck(:occurred_at, :source_doi).uniq { |v| v[1] }
      .group_by { |v| v[0].utc.iso8601[0..3] }
      .map { |k, v| { "year" => k, "total" => v.length } }
      .sort_by { |h| h["year"] }
  end


```

`occurred_at` is updated by the EventData agent and thus cannot be used to bin results.

### Steps to Reproduce

query for 

```
{
  work(id: "10.3334/cdiac/00001_v2015"){
    publicationYear
    citationCount
    citationsOverTime{
      year
      total
    }
    citations{
			published{
        id
        count
      }
    }
        references{
published{
        id
        count
      }
    }
  }
}
```

### Context (Environment)

Citation_year was implemented back in august 2019. look at 

- https://github.com/datacite/lupo/issues/313
- https://github.com/datacite/lupo/pull/330
- https://github.com/datacite/lupo/commit/2390b78404792d6aba354f22fff923c930e3dd1b

### Possible Implementation

aggregate citations using `citation_year`

**Comment by mfenner** [comment]
Please keep in mind that we made significant changes to the Event/DOI integration in January 2020, including adding a `citationsOverTime` property. I suggest to make the following changes:

* fix `occured_at` to represent the `published_date` instead of when the event was last updated. The first step is to implement this for all events going forward, updating the existing events can come later.
* don't use `citationsOverTime` right now, but get the time distribution from the `published` facet for works

The problem with `citation_year` is that it is not in the database and therefore currently can't be used to generate `citationsOverTime`. One important driver for the changes in January 2020 was to have this work as much as possible via the database and Rails `has_many` functionality to make the data model simpler and speed up indexing.

**Comment by mfenner** [comment]
This should be fixed as stated above, using `occured_at`: https://github.com/datacite/lupo/issues/652
