### ISSUE TITLE
Citations counts differ between `works` and `work`

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#662]
Another unrelated,  I was expecting these two queries would give me the same number of citations  but they do not. Any Idea of what’s happening here?. as Far as i can see they use the same code to get the counts.

![image](https://user-images.githubusercontent.com/1092861/96693936-1b557f00-1388-11eb-931b-b3b63034e90e.png)

query 1
```
{
  organization(id: "https://ror.org/03yrm5c26") {
    name
    works(first: 50, ids: "10.48321/d14s38") {
      nodes {
        id
        citations(query: "types.resourceTypeGeneral:Text") {
          totalCount
          nodes {
            id
          }
        }
      }
    }
  }
}

```
query 2
```
{
  work(id: "https://doi.org/10.48321/D14S38") {
    id
    citations(query: "types.resourceTypeGeneral:Text") {
      totalCount
      nodes {
        id
      }
    }
  }
}
```

```

**Comment by codycooperross** [comment]
This issue is resolved for this particular DOI, 10.48321/d14s38. I suspect the issue was a mismatch between the ES index (retrieved in the organization query) and the DB (retrieved in the work query). Re-indexes and record updates since then have likely brought the citation count to equivalence (8).
