### ISSUE TITLE
DOI counts per member are not correctly exported to Salesforce

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#740]
For example University of Virginia (UVA).

**Comment by brittadreyer** [comment]
We bill our members based on DOI numbers of the previous year and we send consortia quarterly billing estimates based on the DOI counts of the current year. Therefore the Fabrica/Salesforce synchronization process includes new member organizations/consortium member organizations and their current year DOIs. Here is one example: https://doi.datacite.org/providers/teyq The consortium account was created June 25th and they are not in Salesforce.  This is true for all members, which Fabrica account has been created after June 18th (Trase, MGWY was the last one to synch)  https://doi.datacite.org/providers?page=NaN&sort=-created. 

Additionally, the synch includes the current year DOI numbers of all members/consortium organizations -- this is not synchronizing as well. FAO has registered 57,440 DOIs in 2021 (https://doi.datacite.org/providers/fao/dois) but Salesforce says 41.028 (https://datacite.lightning.force.com/lightning/r/Account/0011U00000DeuquQAB/view) in the field "Current Year DOI Total".

The two issues are very related because if the member organization is not in Salesforce -- the DOI numbers cannot be pushed into the record.

**Comment by mfenner** [comment]
Addressed via #1302.
